# Generated by Django 2.2.2 on 2020-03-14 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_answers', '0001_initial'),
        ('answers', '0001_initial'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('question_type', models.IntegerField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answersId', to='answers.Answers')),
                ('custom_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_answersId', to='custom_answers.Custom_answers')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageId', to='images.Images')),
            ],
        ),
    ]
