# Generated by Django 2.2.2 on 2020-03-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='optionA',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='questions',
            name='optionB',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='questions',
            name='optionC',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='questions',
            name='optionD',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
