# Generated by Django 2.2.2 on 2020-03-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20200316_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='optionA',
            field=models.CharField(blank=True, default=' ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='optionB',
            field=models.CharField(blank=True, default=' ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='optionC',
            field=models.CharField(blank=True, default=' ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='optionD',
            field=models.CharField(blank=True, default=' ', max_length=255, null=True),
        ),
    ]
