# Generated by Django 2.2.2 on 2020-04-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='choice',
        ),
        migrations.AddField(
            model_name='answers',
            name='text_answer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
