# Generated by Django 2.2.2 on 2020-04-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_auto_20200424_1630'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answers',
            table='Answers',
        ),
    ]
