# Generated by Django 2.2.2 on 2020-04-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_auto_20200424_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choiceA', models.BooleanField(null=True)),
                ('choiceB', models.BooleanField(null=True)),
                ('choiceC', models.BooleanField(null=True)),
                ('choiceD', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'multipleanswers',
            },
        ),
        migrations.AlterModelTable(
            name='answers',
            table='answers',
        ),
    ]
