# Generated by Django 2.2.2 on 2020-04-24 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0004_auto_20200424_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='multiple_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='answers.MultipleAnswers'),
        ),
    ]
