# Generated by Django 2.2.2 on 2020-04-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0005_answers_multiple_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipleanswers',
            name='choiceE',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='multipleanswers',
            name='choiceF',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='multipleanswers',
            name='choiceG',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='multipleanswers',
            name='choiceH',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='multipleanswers',
            name='choiceI',
            field=models.BooleanField(null=True),
        ),
    ]
