# Generated by Django 2.2.2 on 2020-04-24 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='images',
            table='Images',
        ),
    ]
