# Generated by Django 2.2.2 on 2020-04-24 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20200424_1630'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='images',
            table='images',
        ),
    ]
