# Generated by Django 2.2.2 on 2020-04-11 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('answers', '0001_initial'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('optionA', models.CharField(blank=True, default=' ', max_length=255, null=True)),
                ('optionB', models.CharField(blank=True, default=' ', max_length=255, null=True)),
                ('optionC', models.CharField(blank=True, default=' ', max_length=255, null=True)),
                ('optionD', models.CharField(blank=True, default=' ', max_length=255, null=True)),
                ('question_type', models.IntegerField()),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answersId', to='answers.Answers')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imageId', to='images.Images')),
            ],
        ),
        migrations.CreateModel(
            name='Questions_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_level', models.IntegerField()),
                ('test_id', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionId', to='questions_detail.Questions')),
            ],
        ),
    ]
