# Generated by Django 2.2.2 on 2020-04-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions_detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questions',
            table='Questions',
        ),
        migrations.AlterModelTable(
            name='questions_detail',
            table='Question_details',
        ),
    ]
