# Generated by Django 2.2.2 on 2020-04-24 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions_detail', '0003_auto_20200424_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionA', models.CharField(blank=True, default=' ', max_length=255, null=True)),
                ('optionB', models.CharField(blank=True, default=' ', max_length=255, null=True)),
                ('optionC', models.CharField(blank=True, default=' ', max_length=255, null=True)),
                ('optionD', models.CharField(blank=True, default=' ', max_length=255, null=True)),
                ('optionE', models.CharField(blank=True, default=' ', max_length=255, null=True)),
                ('optionF', models.CharField(blank=True, default=' ', max_length=255, null=True)),
                ('optionG', models.CharField(blank=True, default=' ', max_length=255, null=True)),
                ('optionH', models.CharField(blank=True, default=' ', max_length=255, null=True)),
                ('optionI', models.CharField(blank=True, default=' ', max_length=255, null=True)),
            ],
            options={
                'db_table': 'options',
            },
        ),
        migrations.RemoveField(
            model_name='questions',
            name='optionA',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='optionB',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='optionC',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='optionD',
        ),
        migrations.AddField(
            model_name='questions',
            name='options',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions_detail.Options'),
            preserve_default=False,
        ),
    ]
